name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*' # Matches version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Set up the Python version you need

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run Unit Tests
        env:
          MOCHI_API_KEY: ${{ secrets.MOCHI_API_KEY }}
        run: poetry run pytest tests/unit

      - name: Run Integration Tests
        env:
          MOCHI_API_KEY: ${{ secrets.MOCHI_API_KEY }}
        run: poetry run pytest tests/integration

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build