name: Python Package Quality Checks

on:
  push:
    branches:
      - main # Set this to your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Set up the Python version you need

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: poetry install

      - name: Docstring Coverage Test
        run: interrogate --fail-under 75 mochi

      - name: Run pytest
        env:
          MOCHI_API_KEY: ${{ secrets.MOCHI_API_KEY }}
        run: poetry run pytest tests/unit

      # - name: Publish to PyPI
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      #   env:
      #     POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      #   run: poetry publish --build
